<a href="https://colab.research.google.com/github/keshav-153/SOC-25/blob/main/Copy_of_reliance_ta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas_ta
!pip install numpy==1.23.5
!pip install --upgrade --no-cache-dir git+https://github.com/rongardF/tvdatafeed.git

Requirement already satisfied: pandas_ta in /usr/local/lib/python3.11/dist-packages (0.3.14b0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from pandas_ta) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->pandas_ta) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->pandas_ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->pandas_ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->pandas_ta) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->pandas_ta) (1.17.0)
Requirement already satisfied: numpy==1.23.5 in /usr/local/lib/python3.11/dist-packages (1.23.5)
Collecting git+https://github.com/rongardF/tvdatafeed.git
  Cloning https://github.com/rongardF/tvdatafeed.git to /tmp/pip-req-build-tnmovn0d
  Running command git clone --filter=blob:none --quiet https://github.com/rongardF/tvdatafeed.git /tmp/pip-req-build-tnmovn0d
  Resolved https://github.com/rongardF/tvdatafeed.git to commit e6f6aaa7de439ac6e454d9b26d2760ded8dc4923
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tvdatafeed==2.1.0) (75.2.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from tvdatafeed==2.1.0) (2.2.2)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.11/dist-packages (from tvdatafeed==2.1.0) (1.8.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from tvdatafeed==2.1.0) (2.32.3)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->tvdatafeed==2.1.0) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->tvdatafeed==2.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->tvdatafeed==2.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->tvdatafeed==2.1.0) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->tvdatafeed==2.1.0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->tvdatafeed==2.1.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->tvdatafeed==2.1.0) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->tvdatafeed==2.1.0) (2025.6.15)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->tvdatafeed==2.1.0) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import pandas_ta as ta
import matplotlib.pyplot as plt
from tvDatafeed import TvDatafeed, Interval

In [ ]:
tv= TvDatafeed(username=None, password=None)

data1 = tv.get_hist(
    symbol="RELIANCE",
    exchange="NSE",
    interval=Interval.in_daily,
    n_bars=100,
)

print(data1)

WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited

                           symbol     open     high      low    close  \
datetime
2025-01-09 03:45:00  NSE:RELIANCE  1267.00  1269.75  1248.05  1254.75
2025-01-10 03:45:00  NSE:RELIANCE  1253.85  1256.75  1236.00  1241.90
2025-01-13 03:45:00  NSE:RELIANCE  1230.00  1245.25  1226.40  1239.85
2025-01-14 03:45:00  NSE:RELIANCE  1244.10  1253.35  1227.25  1238.75
2025-01-15 03:45:00  NSE:RELIANCE  1244.95  1257.00  1241.85  1252.20
...                           ...      ...      ...      ...      ...
2025-05-30 03:45:00  NSE:RELIANCE  1418.00  1430.60  1409.70  1420.90
2025-06-02 03:45:00  NSE:RELIANCE  1412.10  1417.50  1395.60  1413.70
2025-06-03 03:45:00  NSE:RELIANCE  1422.30  1426.50  1403.40  1405.50
2025-06-04 03:45:00  NSE:RELIANCE  1414.70  1425.70  1406.10  1423.50
2025-06-05 03:45:00  NSE:RELIANCE  1428.00  1454.70  1423.60  1442.40

                         volume
datetime
2025-01-09 03:45:00  12794704.0
2025-01-10 03:45:00   8120332.0
2025-01-13 03:45:00  13764861.0
2025-01-14 03:45:00  13095266.0
2025-01-15 03:45:00   9578856.0
...                         ...
2025-05-30 03:45:00  13788484.0
2025-06-02 03:45:00   8098668.0
2025-06-03 03:45:00  11252626.0
2025-06-04 03:45:00   8126827.0
2025-06-05 03:45:00  13716817.0

[100 rows x 6 columns]

In [ ]:
type(data1)

pandas.core.frame.DataFrame

In [ ]:
data1["SMA_20"] = ta.sma(data1.close, length=20)

data1["EMA_20"] = ta.ema(data1.close, length=20)

data1["RSI"] = ta.rsi(data1.close, length=14)

macd = ta.macd(data1.close)
data1 = pd.concat([data1, macd], axis=1)

data1.tail(20)

,symbol,open,high,low,close,volume,SMA_20,EMA_20,RSI,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9
datetime,,,,,,,,,,,,
2025-05-09 03:45:00,NSE:RELIANCE,1385.5,1394.8,1374.5,1377.2,13668904.0,1323.3700,1345.833805,61.638336,43.921193,5.818519,38.102674
2025-05-12 03:45:00,NSE:RELIANCE,1400.0,1439.0,1400.0,1436.5,10674081.0,1336.0850,1354.468681,70.051364,45.636554,6.027104,39.609450
2025-05-13 03:45:00,NSE:RELIANCE,1433.5,1447.7,1412.4,1415.7,11407896.0,1347.6025,1360.300235,64.692165,44.801164,4.153371,40.647793
2025-05-14 03:45:00,NSE:RELIANCE,1420.0,1429.9,1415.5,1424.4,5570160.0,1357.8750,1366.404975,65.868364,44.330119,2.945861,41.384258
2025-05-15 03:45:00,NSE:RELIANCE,1425.0,1461.4,1412.7,1454.2,20177211.0,1368.5800,1374.766406,69.603567,45.833088,3.559064,42.274024
2025-05-16 03:45:00,NSE:RELIANCE,1453.2,1461.0,1447.3,1456.4,9036695.0,1379.4350,1382.541034,69.865753,46.663811,3.511830,43.151981
2025-05-19 03:45:00,NSE:RELIANCE,1452.1,1454.6,1438.2,1440.8,6195791.0,1387.7500,1388.089507,65.548240,45.538438,1.909165,43.629273
2025-05-20 03:45:00,NSE:RELIANCE,1438.2,1445.0,1421.8,1424.6,11270560.0,1394.2050,1391.566697,61.311003,42.845470,-0.627042,43.472512
2025-05-21 03:45:00,NSE:RELIANCE,1423.9,1436.2,1418.1,1429.2,6136364.0,1401.1050,1395.150821,62.060959,40.614280,-2.286586,42.900866
2025-05-22 03:45:00,NSE:RELIANCE,1421.2,1423.8,1396.9,1409.4,12134466.0,1406.5750,1396.507885,56.944257,36.823868,-4.861598,41.685466
2025-05-23 03:45:00,NSE:RELIANCE,1406.6,1433.8,1406.6,1426.8,6474883.0,1412.8350,1399.392849,60.060578,34.822561,-5.490324,40.312885
2025-05-26 03:45:00,NSE:RELIANCE,1432.0,1441.0,1425.1,1434.8,4842944.0,1419.5550,1402.764958,61.442383,33.495924,-5.453569,38.949493
2025-05-27 03:45:00,NSE:RELIANCE,1426.1,1437.0,1413.9,1422.1,12640414.0,1422.2200,1404.606391,58.011116,31.061711,-6.310226,37.371936
2025-05-28 03:45:00,NSE:RELIANCE,1420.1,1422.6,1410.7,1412.9,5944611.0,1422.8800,1405.396258,55.589271,28.066681,-7.444205,35.510885
2025-05-29 03:45:00,NSE:RELIANCE,1412.1,1420.0,1408.6,1417.8,13771917.0,1423.5200,1406.577567,56.627849,25.791182,-7.775763,33.566945
2025-05-30 03:45:00,NSE:RELIANCE,1418.0,1430.6,1409.7,1420.9,13788484.0,1423.4450,1407.941608,57.308065,23.961761,-7.684147,31.645908
2025-06-02 03:45:00,NSE:RELIANCE,1412.1,1417.5,1395.6,1413.7,8098668.0,1422.5650,1408.490027,55.144865,21.681026,-7.971905,29.652932
2025-06-03 03:45:00,NSE:RELIANCE,1422.3,1426.5,1403.4,1405.5,11252626.0,1421.7950,1408.205262,52.704822,18.992918,-8.528011,27.520929
2025-06-04 03:45:00,NSE:RELIANCE,1414.7,1425.7,1406.1,1423.5,8126827.0,1422.6700,1409.661904,57.183472,18.106304,-7.531700,25.638004
2025-06-05 03:45:00,NSE:RELIANCE,1428.0,1454.7,1423.6,1442.4,13716817.0,1424.4400,1412.779818,61.324776,18.713016,-5.539991,24.253006

In [ ]:
data1.columns

Index(['symbol', 'open', 'high', 'low', 'close', 'volume', 'SMA_20', 'EMA_20',
       'RSI', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9'],
      dtype='object')

In [ ]:
cols_to_float = ['MACD_12_26_9', 'MACDs_12_26_9', 'MACDh_12_26_9']
data1[cols_to_float] = data1[cols_to_float].astype(float)

plt.figure(figsize=(12,6))

plt.plot(data1.index,
         data1['MACD_12_26_9'],
         label='MACD',
         color='blue',
         linewidth=1.2)

plt.plot(data1.index,
         data1['MACDs_12_26_9'],
         label='Signal Line',
         color='orange',
         linewidth=1.2)

plt.bar(data1.index,
        data1['MACDh_12_26_9'],
        label='MACD Histogram',
        color='green',
        alpha=0.5)

plt.fill_between(data1.index,
                 data1['MACDs_12_26_9'],
                 data1['MACD_12_26_9'],
                 where=(data1['MACDh_12_26_9']>0),
                 color='green', alpha=0.25, label='Uptrend')

plt.fill_between(data1.index,
                 data1['MACD_12_26_9'],
                 data1['MACDs_12_26_9'],
                 where=(data1['MACDh_12_26_9']<0),
                 color='red', alpha=0.25, label='Downtrend')

plt.title("MACD indicator")
plt.xlabel("Date")
plt.ylabel("MACD Value")
plt.legend(loc='upper left')
plt.grid(True)
plt.tight_layout()

plt.show()

In [ ]:
import pandas_ta as ta
supertrend = ta.supertrend(high=data1.high, low=data1.low, close=data1.close, length=7, multiplier=3)
data1 = pd.concat([data1, supertrend], axis=1)

data1.tail(20)

In [ ]:
d1 = data1.copy()
d1.index = pd.to_datetime(d1.index)

plt.figure(figsize=(15,10))

plt.plot(d1.index, d1['close'], label='Close', color='black', linewidth=1.2)

plt.plot(d1.index, d1['SUPERT_7_3.0'], label='Supertrend', color='blue', linewidth=2)

plt.fill_between(d1.index,
                 d1.low,
                 d1.high,
                 where=(d1['SUPERTd_7_3.0']==1),
                 color='green', alpha=0.1, label='Uptrend')

plt.fill_between(d1.index,
                 d1.low,
                 d1.high,
                 where=(d1['SUPERTd_7_3.0']==-1),
                 color='red', alpha=0.1, label='Downtrend')

plt.title('Supertrend Indicator')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend(loc='upper left')
plt.grid(True)

plt.show()

In [ ]:
d2 = d1[['close', 'EMA_20', 'SMA_20', 'RSI']].copy()

d2['prevRSI'] = d2['RSI'].shift(1)

def rsi_decision(row):
  if row['prevRSI']<30 and row['RSI']>=30: return 'LONG'
  elif row['prevRSI']>70 and row['RSI']<=70: return 'SHORT'
  else: return 'HOLD'

d2['RSI_decision'] = d2.apply(rsi_decision, axis=1)

d2.head(50)

In [ ]:
d3 = d1[['close', 'high',
         'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
         'SUPERT_7_3.0', 'SUPERTd_7_3.0', 'SUPERTl_7_3.0', 'SUPERTs_7_3.0']].copy()

d3['prev_macd'] = d3['MACD_12_26_9'].shift(1)
d3['prev_signal'] = d3['MACDs_12_26_9'].shift(1)

def macd_decision(row):
    if row['prev_macd'] < row['prev_signal'] and row['MACD_12_26_9'] >= row['MACDs_12_26_9']:
        return 'LONG'
    elif row['prev_macd'] > row['prev_signal'] and row['MACD_12_26_9'] <= row['MACDs_12_26_9']:
        return 'SHORT'
    else:
        return 'HOLD'

d3['MACD_decision'] = d3.apply(macd_decision, axis=1)

d3[['close', 'MACD_12_26_9', 'MACDs_12_26_9', 'MACD_decision']].tail(45)

In [ ]:
d3['prev_supert_dir'] = d3['SUPERTd_7_3.0'].shift(1)

def supert_decision(row):
    if row['prev_supert_dir'] == -1 and row['SUPERTd_7_3.0'] == 1:
        return 'LONG'
    elif row['prev_supert_dir'] == 1 and row['SUPERTd_7_3.0'] == -1:
        return 'SHORT'
    else:
        return 'HOLD'

d3['SUPERT_decision'] = d3.apply(supert_decision, axis=1)


d3[['close','SUPERT_7_3.0', 'SUPERTd_7_3.0', 'MACD_decision']].tail(45)

                       close  SUPERT_7_3.0  SUPERTd_7_3.0 MACD_decision
datetime
2025-03-28 03:45:00  1275.10   1228.822696              1          HOLD
2025-04-01 03:45:00  1252.60   1228.822696              1          HOLD
2025-04-02 03:45:00  1251.15   1228.822696              1          HOLD
2025-04-03 03:45:00  1248.70   1228.822696              1         SHORT
2025-04-04 03:45:00  1204.70   1297.519517             -1          HOLD
2025-04-07 03:45:00  1165.70   1248.605073             -1          HOLD
2025-04-08 03:45:00  1182.20   1248.605073             -1          HOLD
2025-04-09 03:45:00  1185.35   1248.605073             -1          HOLD
2025-04-11 03:45:00  1218.95   1248.605073             -1          HOLD
2025-04-15 03:45:00  1240.10   1248.605073             -1          HOLD
2025-04-16 03:45:00  1239.30   1248.605073             -1          HOLD
2025-04-17 03:45:00  1274.50   1153.321713              1          LONG
2025-04-21 03:45:00  1295.50   1183.211463              1          HOLD
2025-04-22 03:45:00  1291.20   1201.210017              1          HOLD
2025-04-23 03:45:00  1300.00   1206.394411              1          HOLD
2025-04-24 03:45:00  1301.60   1214.766775              1          HOLD
2025-04-25 03:45:00  1300.40   1219.921449              1          HOLD
2025-04-28 03:45:00  1368.80   1241.260948              1          HOLD
2025-04-29 03:45:00  1399.70   1281.430776              1          HOLD
2025-04-30 03:45:00  1405.00   1281.430776              1          HOLD
2025-05-02 03:45:00  1422.40   1312.561421              1          HOLD
2025-05-05 03:45:00  1431.30   1335.581281              1          HOLD
2025-05-06 03:45:00  1420.90   1335.581281              1          HOLD
2025-05-07 03:45:00  1406.00   1335.581281              1          HOLD
2025-05-08 03:45:00  1407.00   1335.581281              1          HOLD
2025-05-09 03:45:00  1377.20   1335.581281              1          HOLD
2025-05-12 03:45:00  1436.50   1335.581281              1          HOLD
2025-05-13 03:45:00  1415.70   1335.581281              1          HOLD
2025-05-14 03:45:00  1424.40   1335.581281              1          HOLD
2025-05-15 03:45:00  1454.20   1335.808131              1          HOLD
2025-05-16 03:45:00  1456.40   1361.499844              1          HOLD
2025-05-19 03:45:00  1440.80   1361.499844              1          HOLD
2025-05-20 03:45:00  1424.60   1361.499844              1         SHORT
2025-05-21 03:45:00  1429.20   1361.499844              1          HOLD
2025-05-22 03:45:00  1409.40   1361.499844              1          HOLD
2025-05-23 03:45:00  1426.80   1361.499844              1          HOLD
2025-05-26 03:45:00  1434.80   1361.499844              1          HOLD
2025-05-27 03:45:00  1422.10   1361.499844              1          HOLD
2025-05-28 03:45:00  1412.90   1361.499844              1          HOLD
2025-05-29 03:45:00  1417.80   1361.499844              1          HOLD
2025-05-30 03:45:00  1420.90   1361.499844              1          HOLD
2025-06-02 03:45:00  1413.70   1361.499844              1          HOLD
2025-06-03 03:45:00  1405.50   1361.499844              1          HOLD
2025-06-04 03:45:00  1423.50   1361.499844              1          HOLD
2025-06-05 03:45:00  1442.40   1369.170304              1          HOLD